name: Authenticate to Cloud Provider

on:
  workflow_call:
    inputs:
      provider:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      GCP_SERVICE_ACCOUNT_KEY:
        required: false

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with AWS
        if: inputs.provider == 'AWS'
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Authenticate with GCP
        if: inputs.provider == 'GCP'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

